/// <reference path="../.astro/types.d.ts" />

// Allow TypeScript to resolve .astro file imports in test files.
// At runtime Vite handles these via Astro's plugin; this declaration
// keeps the language server happy without affecting compilation output.
declare module "*.astro" {
  import type { AstroComponentFactory } from "astro/runtime/server/index.js";
  const component: AstroComponentFactory;
  export default component;
}

interface ImportMetaEnv {
  /** Facebook App ID for `fb:app_id` (Open Graph). Set in Vercel / `.env`. */
  readonly PUBLIC_FB_APP_ID?: string;
  /** Sanity project ID. Defaults to the HackMI project in `astro.config.mjs` if unset. */
  readonly PUBLIC_SANITY_PROJECT_ID?: string;
  /** Sanity dataset. Defaults to `production` in `astro.config.mjs` if unset. */
  readonly PUBLIC_SANITY_DATASET?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

/**
 * `sanity:client` is a virtual module exposed by `@sanity/astro` at build time.
 * We declare it here so TS doesn't choke when it's imported from `src/lib/sanity/`.
 * Keep the shape minimal; richer types are generated by `@sanity/astro` itself.
 */
declare module "sanity:client" {
  import type { SanityClient } from "@sanity/client";
  export const sanityClient: SanityClient;
}
